### PR TITLE
Release 1.0.0.Alpha1

### PR DESCRIPTION
**Pull request by rmanibus**

### CODE REVIEW

**Comment by gastaldi** [comment]
Don't forget to publish the guide URL: https://github.com/quarkiverse/quarkus-bucket4j/blob/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml#L10

**Comment by gastaldi** [comment]
I created https://github.com/quarkiverse/quarkiverse-docs/pull/79 to publish the docs

**Comment by rmanibus** [comment]
> I created [quarkiverse/quarkiverse-docs#79](https://github.com/quarkiverse/quarkiverse-docs/pull/79) to publish the docs

Thanks a lot @gastaldi

**Comment by gastaldi** [comment]
@rmanibus one thing that I do manually in the Quarkiverse extensions I maintain is to create a GitHub release (that looks nicer on Dependabot PRs that depend on your library)

**Pull request merged**
