### PR TITLE
Include guide URL

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by rmanibus** [comment]
@gastaldi do I need to restart the CI after this ?

**Comment by gastaldi** [comment]
Hm, I'm investigating what caused the tag push to fail. Your artifacts are in maven central, though

**Comment by gastaldi** [comment]
> @gastaldi do I need to restart the CI after this ?

You need another Alpha (or we can change in the registry, but it's easier to release another Alpha) :)

**Comment by gastaldi** [comment]
Ah that explains it, the release process does not `git rebase` before pushing :)

**Pull request merged**
