### PR TITLE
Release 1.0.0.Alpha2

### PR DESCRIPTION
**Pull request by rmanibus**

### CODE REVIEW

**Comment by rmanibus** [comment]
@gastaldi it went through this time. Do I need to create a release ?

**Comment by gastaldi** [comment]
Although not required, it would be nice, since it contains the release notes and will look better in Dependabot PRs

**Comment by rmanibus** [comment]
@gastaldi is there an official way to socialize new extensions and request for feedback ?
If not can I just post on zulip ?

**Comment by gastaldi** [comment]
@rmanibus we haven't really "officialized" that step. Zulip is fine, you can also send a message to our quarkus-dev mailing list

**Pull request merged**
